build: main.cpp graph_gen_store_load.cpp a_star.cpp utilities.cpp menu.cpp
	g++ -Wall main.cpp graph_gen_store_load.cpp a_star.cpp utilities.cpp menu.cpp -o main -pthread

run:
	@touch graph
	@./main graph